import express from 'express';
import { pool } from '../config/db.js';
import { protect } from '../middleware/auth.js';
const router=express.Router();
async function getCart(userId){ const [rows]=await pool.query(`SELECT ci.cart_item_id AS cartItemId,ci.product_id AS _id,ci.quantity,p.product_name AS name,p.price,p.image,p.stock FROM cart c JOIN cart_items ci ON ci.cart_id=c.cart_id JOIN products p ON p.product_id=ci.product_id WHERE c.user_id=? ORDER BY ci.cart_item_id DESC`,[userId]); return rows; }
async function cartId(userId){ const [r]=await pool.query('SELECT cart_id FROM cart WHERE user_id=? LIMIT 1',[userId]); if(r.length)return r[0].cart_id; const [n]=await pool.query('INSERT INTO cart(user_id) VALUES(?)',[userId]); return n.insertId; }
router.get('/',protect,async(req,res)=>res.json({items:await getCart(req.user.user_id)}));
router.post('/add',protect,async(req,res)=>{ const {productId,quantity=1}=req.body; const [p]=await pool.query('SELECT product_id,stock FROM products WHERE product_id=?',[productId]); if(!p.length)return res.status(404).json({message:'Product not found'}); const cid=await cartId(req.user.user_id); const [i]=await pool.query('SELECT cart_item_id,quantity FROM cart_items WHERE cart_id=? AND product_id=?',[cid,productId]); const next=(i[0]?.quantity||0)+Number(quantity); if(next>p[0].stock)return res.status(400).json({message:`Only ${p[0].stock} in stock`}); if(i.length)await pool.query('UPDATE cart_items SET quantity=? WHERE cart_item_id=?',[next,i[0].cart_item_id]); else await pool.query('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES(?,?,?)',[cid,productId,quantity]); res.json({items:await getCart(req.user.user_id)}); });
router.patch('/item/:productId',protect,async(req,res)=>{ const q=Math.max(0,Number(req.body.quantity)); const [c]=await pool.query('SELECT cart_id FROM cart WHERE user_id=?',[req.user.user_id]); if(!c.length)return res.json({items:[]}); if(q===0)await pool.query('DELETE FROM cart_items WHERE cart_id=? AND product_id=?',[c[0].cart_id,req.params.productId]); else await pool.query('UPDATE cart_items SET quantity=? WHERE cart_id=? AND product_id=?',[q,c[0].cart_id,req.params.productId]); res.json({items:await getCart(req.user.user_id)}); });
router.delete('/',protect,async(req,res)=>{const [c]=await pool.query('SELECT cart_id FROM cart WHERE user_id=?',[req.user.user_id]);if(c.length)await pool.query('DELETE FROM cart_items WHERE cart_id=?',[c[0].cart_id]);res.json({items:[]});});
export default router;
