import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { connectDB } from './config/db.js';
import auth from './routes/auth.js';
import products from './routes/products.js';
import cart from './routes/cart.js';
import orders from './routes/orders.js';
import customizations from './routes/customizations.js';
import categories from './routes/categories.js';
const app=express();
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'}));
app.use(express.json({limit:'5mb'}));
app.use('/uploads',express.static('uploads'));
app.get('/api/health',(req,res)=>res.json({ok:true,app:'ECOBLOOM API',database:'MySQL'}));
app.use('/api/auth',auth);app.use('/api/products',products);app.use('/api/cart',cart);app.use('/api/orders',orders);app.use('/api/customizations',customizations);app.use('/api/categories',categories);
const port=process.env.PORT||5000;
connectDB().then(()=>app.listen(port,()=>console.log(`API running on http://localhost:${port}`))).catch(e=>{console.error('MySQL connection failed:',e.message);process.exit(1)});
