import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { LayoutDashboard, ShoppingBag, Package, Tags, Users, CreditCard, Palette, LogOut, Plus, Trash2, Pencil, X } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../context/AuthContext';

const ORDER_STATUSES=['PLACED','PROCESSING','SHIPPED','DELIVERED','CANCELLED'];
const CUSTOM_STATUSES=['NEW','REVIEWING','QUOTED','APPROVED','COMPLETED','REJECTED'];

export default function Admin(){
 const {logout,user}=useAuth(); const [tab,setTab]=useState('dashboard'); const [products,setProducts]=useState([]),[orders,setOrders]=useState([]),[custom,setCustom]=useState([]),[categories,setCategories]=useState([]),[customers,setCustomers]=useState([]),[payments,setPayments]=useState([]); const [editing,setEditing]=useState(null); const [showAdd,setShowAdd]=useState(false); const [loading,setLoading]=useState(true);
 const empty={name:'',category:'Seed Paper',price:'',description:'',image:'',seedType:'Mixed flowers',stock:20,gsm:250,size:'A5',featured:false}; const [form,setForm]=useState(empty);
 const load=async()=>{setLoading(true);try{const [p,o,c,cat,cu,pa]=await Promise.all([api('/products'),api('/orders'),api('/customizations'),api('/categories'),api('/auth/users'),api('/orders/payments')]);setProducts(p);setOrders(o);setCustom(c);setCategories(cat);setCustomers(cu);setPayments(pa);}catch(e){console.error(e);}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const revenue=useMemo(()=>payments.filter(x=>x.payment_status==='SUCCESS').reduce((s,x)=>s+Number(x.amount),0),[payments]);
 const saveProduct=async e=>{e.preventDefault();try{const body={...form,price:Number(form.price),stock:Number(form.stock),gsm:Number(form.gsm)};if(editing)await api('/products/'+editing,{method:'PUT',body:JSON.stringify(body)});else await api('/products',{method:'POST',body:JSON.stringify(body)});setForm(empty);setEditing(null);setShowAdd(false);load()}catch(e){alert(e.message)}};
 const remove=async id=>{if(confirm('Delete this product?')){await api('/products/'+id,{method:'DELETE'});load()}};
 const orderStatus=async(id,value)=>{await api(`/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({orderStatus:value})});load()};
 const customStatus=async(id,value)=>{await api(`/customizations/${id}/status`,{method:'PATCH',body:JSON.stringify({status:value})});load()};
 const edit=p=>{setForm({name:p.name,category:p.category||'Seed Paper',price:p.price,description:p.description||'',image:p.image||'',seedType:p.seedType||'',stock:p.stock,gsm:p.gsm||250,size:p.size||'',featured:!!p.featured});setEditing(p._id);setShowAdd(true);setTab('products')};
 if(loading)return <main className="adminShell"><div className="adminLoading">Loading admin panel…</div></main>;
 return <main className="adminShell">
  <aside className="adminSidebar"><div className="adminBrand"><span>🌱</span><div><strong>ECOBLOOM</strong><small>OWNER PANEL</small></div></div><div className="adminUser">{user?.name}<small>{user?.email}</small></div><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}><LayoutDashboard/> Dashboard</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}><ShoppingBag/> Orders <b>{orders.length}</b></button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}><Package/> Products <b>{products.length}</b></button><button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}><Tags/> Categories</button><button className={tab==='custom'?'active':''} onClick={()=>setTab('custom')}><Palette/> Customizations <b>{custom.filter(x=>x.status==='NEW').length}</b></button><button className={tab==='customers'?'active':''} onClick={()=>setTab('customers')}><Users/> Customers</button><button className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}><CreditCard/> Payments</button><div className="adminBottom"><Link to="/Store" target="_blank">View storefront ↗</Link><button onClick={logout}><LogOut/> Logout</button></div></aside>
  <section className="adminMain"><header className="adminTop"><div><span className="eyebrow">OWNER CONTROL CENTER</span><h1>{tab==='dashboard'?'Dashboard':tab==='custom'?'Customization Requests':tab[0].toUpperCase()+tab.slice(1)}</h1></div><button className="refreshBtn" onClick={load}>Refresh</button></header>
  {tab==='dashboard'&&<Dashboard products={products} orders={orders} custom={custom} customers={customers} revenue={revenue} setTab={setTab}/>}
  {tab==='orders'&&<OrdersPanel orders={orders} orderStatus={orderStatus}/>}
  {tab==='products'&&<ProductsPanel products={products} form={form} setForm={setForm} saveProduct={saveProduct} remove={remove} edit={edit} showAdd={showAdd} setShowAdd={setShowAdd} editing={editing} setEditing={setEditing}/>}
  {tab==='categories'&&<CategoriesPanel categories={categories} load={load}/>}
  {tab==='custom'&&<CustomPanel custom={custom} customStatus={customStatus}/>}
  {tab==='customers'&&<CustomersPanel customers={customers}/>}
  {tab==='payments'&&<PaymentsPanel payments={payments}/>}
  </section></main>
}

function Dashboard({products,orders,custom,customers,revenue,setTab}){return <><div className="dashStats"><button onClick={()=>setTab('products')}><Package/><b>{products.length}</b><span>Products</span></button><button onClick={()=>setTab('orders')}><ShoppingBag/><b>{orders.length}</b><span>Total Orders</span></button><button onClick={()=>setTab('custom')}><Palette/><b>{custom.filter(x=>x.status==='NEW').length}</b><span>New Custom Requests</span></button><button onClick={()=>setTab('customers')}><Users/><b>{customers.length}</b><span>Customers</span></button><div className="dashRevenue"><CreditCard/><b>₹{revenue.toFixed(2)}</b><span>Successful payments</span></div></div><div className="adminTwo"><div className="adminPanel"><div className="panelTitle"><h2>Recent Orders</h2><button onClick={()=>setTab('orders')}>View all →</button></div>{orders.slice(0,6).map(o=><div className="tableRow" key={o._id}><span><b>#{o._id}</b><small>{o.user?.name}</small></span><b>₹{Number(o.total).toFixed(2)}</b><em className="status">{o.orderStatus}</em></div>)}</div><div className="adminPanel"><div className="panelTitle"><h2>Low Stock</h2><button onClick={()=>setTab('products')}>Manage →</button></div>{products.filter(p=>p.stock<=10).slice(0,6).map(p=><div className="tableRow" key={p._id}><span><b>{p.name}</b><small>{p.category}</small></span><em className="stockLow">{p.stock} left</em></div>)}{!products.some(p=>p.stock<=10)&&<p className="muted">All products have healthy stock.</p>}</div></div></>}

function OrdersPanel({orders,orderStatus}){return <div className="adminPanel wide"><div className="panelTitle"><h2>All Orders</h2><span>{orders.length} orders</span></div>{!orders.length&&<p className="muted">No orders yet.</p>}<div className="adminTable">{orders.map(o=><div className="adminOrderFull" key={o._id}><div><b>#{o._id}</b><small>{new Date(o.createdAt).toLocaleString()}</small></div><div><b>{o.user?.name}</b><small>{o.user?.email}</small><small>{o.shippingAddress?.address}, {o.shippingAddress?.city} {o.shippingAddress?.pincode}</small></div><div><b>{o.items.length} item(s)</b><small>{o.items.map(i=>`${i.name} × ${i.quantity}`).join(', ')}</small></div><div><strong>₹{Number(o.total).toFixed(2)}</strong><small>{o.paymentMethod} • {o.paymentStatus}</small></div><select value={o.orderStatus} onChange={e=>orderStatus(o.order_id,e.target.value)}>{ORDER_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>)}</div></div>}

function ProductsPanel({products,form,setForm,saveProduct,remove,edit,showAdd,setShowAdd,editing,setEditing}){return <><div className="panelTitle"><h2>Products</h2><button className="primary" onClick={()=>{setForm({name:'',category:'Seed Paper',price:'',description:'',image:'',seedType:'Mixed flowers',stock:20,gsm:250,size:'A5',featured:false});setEditing(null);setShowAdd(true)}}><Plus size={17}/> Add Product</button></div>{showAdd&&<form className="adminForm" onSubmit={saveProduct}><div className="formRow"><input required placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Seed Paper','Greeting Cards','Wedding Invitations','Bookmarks','Gift Tags','Gift Kits','Stationery','Corporate Gifts'].map(x=><option key={x}>{x}</option>)}</select></div><div className="formRow"><input required type="number" min="0" placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input type="number" min="0" placeholder="Stock" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input placeholder="Size" value={form.size} onChange={e=>setForm({...form,size:e.target.value})}/></div><div className="formRow"><input placeholder="Seed type" value={form.seedType} onChange={e=>setForm({...form,seedType:e.target.value})}/><input type="number" placeholder="GSM" value={form.gsm} onChange={e=>setForm({...form,gsm:e.target.value})}/><input placeholder="Image URL" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></div><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="formActions"><button className="primary">{editing?'Update product':'Add product'}</button><button type="button" className="ghostBtn" onClick={()=>{setShowAdd(false);setEditing(null)}}>Cancel</button></div></form>}<div className="productAdminGrid">{products.map(p=><div className="productAdminCard" key={p._id}><img src={p.image} alt=""/><div><span>{p.category}</span><h3>{p.name}</h3><p>₹{p.price} • Stock {p.stock} • {p.seedType}</p><div><button onClick={()=>edit(p)}><Pencil size={15}/> Edit</button><button onClick={()=>remove(p._id)}><Trash2 size={15}/> Delete</button></div></div></div>)}</div></>}

function CategoriesPanel({categories,load}){const[name,setName]=useState('');const add=async e=>{e.preventDefault();if(!name.trim())return;try{await api('/categories',{method:'POST',body:JSON.stringify({name:name.trim()})});setName('');load()}catch(e){alert(e.message)}};const remove=async id=>{if(confirm('Delete category?')){try{await api('/categories/'+id,{method:'DELETE'});load()}catch(e){alert(e.message)}}};return <div className="adminPanel wide"><div className="panelTitle"><h2>Categories</h2><span>{categories.length} categories</span></div><form className="inlineAdd" onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="New category name"/><button className="primary">Add</button></form><div className="categoryGrid">{categories.map(c=><div key={c.category_id}><b>{c.category_name}</b><small>{c.description||'ECOBLOOM product category'}</small><button onClick={()=>remove(c.category_id)}><Trash2 size={14}/></button></div>)}</div></div>}

function CustomPanel({custom,customStatus}){return <div className="adminPanel wide"><div className="panelTitle"><h2>Customization Requests</h2><span>{custom.length} requests</span></div>{!custom.length&&<p className="muted">No customization requests yet.</p>}{custom.map(c=><div className="customAdminCard" key={c.request_id}><div><b>#{c.request_id} • {c.request_title}</b><small>{c.product_name||'Custom product'} • {c.user_name} • {c.user_email}</small><p>{c.custom_text||'No special instructions.'}</p><small>Quantity: {c.quantity} • Size: {c.size||'—'} • Paper: {c.paper_type||'—'} • Seeds: {c.seed_type||'—'}</small>{c.uploaded_design&&<a href={`http://localhost:5000${c.uploaded_design}`} target="_blank" rel="noreferrer">View uploaded artwork ↗</a>}</div><select value={c.status} onChange={e=>customStatus(c.request_id,e.target.value)}>{CUSTOM_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>)}</div>}

function CustomersPanel({customers}){return <div className="adminPanel wide"><div className="panelTitle"><h2>Customers</h2><span>{customers.length} accounts</span></div><div className="customerGrid">{customers.map(c=><div key={c.user_id}><Users/><div><b>{c.name}</b><small>{c.email}</small><small>{c.phone||'No phone'}</small></div></div>)}</div></div>}

function PaymentsPanel({payments}){return <div className="adminPanel wide"><div className="panelTitle"><h2>Payments</h2><span>{payments.length} payment records</span></div><div className="adminTable">{payments.map(p=><div className="paymentRow" key={p.payment_id}><span><b>Payment #{p.payment_id}</b><small>Order #{p.order_id}</small></span><strong>₹{Number(p.amount).toFixed(2)}</strong><span>{p.payment_method}</span><em className={p.payment_status==='SUCCESS'?'paid':'pending'}>{p.payment_status}</em><small>{new Date(p.payment_date).toLocaleString()}</small></div>)}</div></div>}
